#!/bin/bash -l
#SBATCH --job-name="NeRF_job_Gopher"
#SBATCH --ntasks=128
#SBATCH --output=NeRF.out
#SBATCH --error=NeRF.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=huxxx853@umn.edu
#SBATCH --time=24:00:00
#SBATCH -p interactive-gpu
#SBATCH --gres=gpu:a40:1
​
pip install h5py
pip install typing-extensions
pip install wheel
pip install -r requirements.txt
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
python run_nerf.py --config configs/GopherSmall.txt
